# Generated by Django 4.1.1 on 2022-10-02 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avartar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avartar',
            new_name='avatar',
        ),
    ]
